language: android
jdk: oraclejdk8
script: ./gradlew clean build test

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - build-tools-29.0.2
    - build-tools-30.0.1
    - android-28
    - android-29
    - android-30
    - extra-google-m2repository
    - extra-android-m2repository

env:
  global:
    - API=30 # Android API default
